### ISSUE TITLE
Tutorial Simplification

### ISSUE THREAD

**Issue by kylemath** [kylemath/mne-python#13]
I would like the tutorial to print 1/3 as many plots. 
I think the best option is to not plot separately for montage a and b, but to combine them and only plot the combo

I also have an issue on my machine that the ones with subplots don't work, the first panel is plotted with a bunch of white squares for the others, than the other figures appear one by one, but blank, I assume the same isn't happening for you?

I think this is an issue with my matplotlib backend

**Comment by kuziekj** [comment]
Yeah that sounds like a good idea. I'll make those changes in the 'clean_up' branch, don't think we need a new one.

Yeah my subplots seem to work fine. Do you get the same issue if you run the plot_70 tutorial? Pretty sure I just modified what was in there.

**Comment by kuziekj** [comment]
this should now plot only combined montages, here's the PR: https://github.com/kylemath/mne-python/pull/16
