### ISSUE TITLE
optical density changes

### ISSUE THREAD

**Issue by kylemath** [kylemath/mne-python#15]
mne/preprocessing/nirs/_optical_density.py

what do these changes you made do: 
<img width="614" alt="Screen Shot 2020-06-16 at 1 35 10 AM" src="https://user-images.githubusercontent.com/3662613/84745332-46a70800-af69-11ea-8d4f-7d9fc7266d69.png">

**Comment by kuziekj** [comment]
the original code assumed the data was fnirs_raw (like line 31) and this was giving an error when passing phase data...now that I think about it I don't think we'll ever pass phase data to this now.

I'll change this back to what the original was.

**Comment by kuziekj** [comment]
this should be addressed in this PR: https://github.com/kylemath/mne-python/pull/16
