### ISSUE TITLE
Reading multiple boxy data files

### ISSUE THREAD

**Issue by kuziekj** [kylemath/mne-python#4]
Right now 'read_raw_boxy' will only read data from a single boxy data file.

Since .mtg and .elp files contain channel coordinates for all conditions/blocks for a single participant, all data files associated with a participant should be imported.

Perhaps the best way is to point to a folder and find all relevant files for a given participant (similar to nirx.py). We need to make sure that file names are consistent so that each file can be easily found.

**Comment by kylemath** [comment]
so far we just load exp0001a.001
in reality there are 16 blocks with this montage, exp0001a.001, 002, ... 016
there are also usually multiple montages, so exp0001a.001, exp0001b.001, exp0001c.001, etc.

**Comment by kylemath** [comment]
first step is making a new branch from importBOXY
then I will change the link to the dataset to match the larger dataset 
then we start to play around

**Comment by kuziekj** [comment]
so just reading all the files in a given folder should find everything (since it seems nirx.py checks for specific extensions) but we need a way to keep track of how many blocks and montages we we have for each participant.

do we still want to follow the naming scheme of the old files or try something else?

maybe something like exp001a001.csv (so experiment name, participant number, montage letter, block number)? this way we only have to look for a single extension (csv in this case) rather than for .001, .002, etc.

**Comment by kylemath** [comment]
nope
we want to keep the naming scheme for backwards compatibility with datasets

so we want to look through the folder
count up from 001
until there is no file named say 017
then we know there are 16 blocks

then we want to count up by a b c d and do the same

then you make a list of keys like there are now
but '001', '002', up to '016' for each montage

**Comment by kylemath** [comment]
new branch and PR here: https://github.com/kylemath/mne-python/pull/5
